name: tests-tickets

on:
  pull_request:
    paths:
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
      - run: cd tickets && npm install && npm run test:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
